# Generated by Django 5.2 on 2025-04-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('mascota', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino'), ('Otro', 'Otro')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_reproductivo', models.CharField(choices=[('Entero', 'Entero'), ('Esterilizado', 'Esterilizado')], max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='vetapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('anamnesis_remota', models.TextField()),
                ('anamnesis_actual', models.TextField()),
                ('pc', models.TextField()),
                ('tllc', models.TextField()),
                ('oidos', models.TextField()),
                ('ojos', models.TextField()),
                ('boca', models.TextField()),
                ('linfonodo_submandibular', models.TextField()),
                ('rt', models.CharField(max_length=10)),
                ('fc', models.CharField(max_length=10)),
                ('fr', models.CharField(max_length=10)),
                ('pulso_femoral', models.TextField()),
                ('palpacion_abdominal', models.TextField()),
                ('miembro_reproductor', models.TextField()),
                ('linfonodo_inguinal', models.TextField()),
                ('pelaje', models.TextField()),
                ('temperatura', models.CharField(max_length=10)),
                ('tratamiento', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('receta', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetapp.cliente')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vetapp.mascota')),
            ],
        ),
    ]
