# Generated by Django 5.2 on 2025-04-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='vetapp.mascota'),
        ),
    ]
