# Generated by Django 5.2 on 2025-05-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0002_alter_ficha_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='cc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
