# Generated by Django 5.2 on 2025-05-07 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetapp', '0003_ficha_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_visita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
